In [1]:
import pandas as pd
import joblib
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_parquet("../data/interim/02_cleaned.parquet")

print("Dataset Shape:", df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/interim/02_cleaned.parquet'

In [3]:
import os

print(os.getcwd())

/Users/adithyant/Desktop/internship/zelbytes-yield-/notebooks

In [5]:
import os

print(os.listdir("../data/interim"))

['01_loaded.parquet']

In [8]:
df = pd.read_parquet("../data/interim/01_loaded.parquet")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (120, 5)

            timestamp  temperature   humidity          co2   yield_kg
0 2025-01-01 00:00:00    25.993428  68.317314  1080.786751  13.825416
1 2025-01-01 01:00:00    24.723471  85.487572  1118.317068  13.813510
2 2025-01-01 02:00:00    26.295377  72.872410  1156.002137  14.305479
3 2025-01-01 03:00:00    28.046060  82.130704   935.198063  13.021004
4 2025-01-01 04:00:00    24.531693  82.173540   950.233181  13.681953

In [9]:
import pandas as pd
import joblib
from sklearn.preprocessing import MinMaxScaler

df = pd.read_parquet("../data/interim/01_loaded.parquet")

print(df.shape)
df.head()

(120, 5)

            timestamp  temperature   humidity          co2   yield_kg
0 2025-01-01 00:00:00    25.993428  68.317314  1080.786751  13.825416
1 2025-01-01 01:00:00    24.723471  85.487572  1118.317068  13.813510
2 2025-01-01 02:00:00    26.295377  72.872410  1156.002137  14.305479
3 2025-01-01 03:00:00    28.046060  82.130704   935.198063  13.021004
4 2025-01-01 04:00:00    24.531693  82.173540   950.233181  13.681953

In [10]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

df = df.sort_values("timestamp").reset_index(drop=True)

df.head()

            timestamp  temperature   humidity          co2   yield_kg
0 2025-01-01 00:00:00    25.993428  68.317314  1080.786751  13.825416
1 2025-01-01 01:00:00    24.723471  85.487572  1118.317068  13.813510
2 2025-01-01 02:00:00    26.295377  72.872410  1156.002137  14.305479
3 2025-01-01 03:00:00    28.046060  82.130704   935.198063  13.021004
4 2025-01-01 04:00:00    24.531693  82.173540   950.233181  13.681953

In [11]:
X = df[["temperature", "humidity", "co2"]]

y = df["yield_kg"]

print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (120, 3)
y Shape: (120,)

In [12]:
split_idx = int(len(df) * 0.8)

X_train = X.iloc[:split_idx]
X_test = X.iloc[split_idx:]

y_train = y.iloc[:split_idx]
y_test = y.iloc[split_idx:]

In [13]:
print("Train Rows:", len(X_train))
print("Test Rows :", len(X_test))

print("\nTrain Period:")
print(df.iloc[0]["timestamp"], "to",
      df.iloc[split_idx-1]["timestamp"])

print("\nTest Period:")
print(df.iloc[split_idx]["timestamp"], "to",
      df.iloc[-1]["timestamp"])

Train Rows: 96
Test Rows : 24

Train Period:
2025-01-01 00:00:00 to 2025-01-04 23:00:00

Test Period:
2025-01-05 00:00:00 to 2025-01-05 23:00:00

In [14]:
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

print("Scaling completed")

Scaling completed

In [15]:
joblib.dump(scaler, "../models/scaler.joblib")

print("Scaler saved successfully")

Scaler saved successfully

In [16]:
pd.DataFrame(
    X_train_scaled,
    columns=X.columns
).to_csv("../data/processed/X_train.csv", index=False)

pd.DataFrame(
    X_test_scaled,
    columns=X.columns
).to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)

y_test.to_csv("../data/processed/y_test.csv", index=False)

print("All files saved successfully")

All files saved successfully

In [17]:
import os

print(os.listdir("../data/processed"))
print(os.listdir("../models"))

['02_cleaned.csv', '.gitkeep', 'X_train.csv', 'y_train.csv', '02_cleaned.parquet', 'y_test.csv', 'X_test.csv']
['.gitkeep', 'scaler.joblib']

In [18]:
df = pd.read_parquet("../data/processed/02_cleaned.parquet")

In [19]:
print("Train Start:", df.iloc[0]["timestamp"])
print("Train End:", df.iloc[split_idx-1]["timestamp"])

print("Test Start:", df.iloc[split_idx]["timestamp"])
print("Test End:", df.iloc[-1]["timestamp"])

Train Start: 2025-01-01 00:00:00
Train End: 2025-01-04 23:00:00
Test Start: 2025-01-05 00:00:00
Test End: 2025-01-05 23:00:00